import { Component } from '@angular/core';
import { IonApp, IonRouterOutlet } from '@ionic/angular/standalone';
import { addIcons } from 'ionicons';
import {
  alarmOutline,
  archiveOutline,
  calendarClearOutline,
  calendarOutline,
  camera,
  cameraOutline,
  carOutline,
  carSport,
  checkmarkCircle,
  closeOutline,
  cloudDoneOutline,
  cloudOfflineOutline,
  copyOutline,
  createOutline,
  eyeOutline,
  list,
  listOutline,
  locateOutline,
  locationOutline,
  map,
  mapOutline,
  navigate,
  navigateOutline,
  notificationsOutline,
  refreshOutline,
  settings,
  settingsOutline,
  stopCircle,
  timeOutline,
  trashBinOutline,
  trashOutline,
  warningOutline,
} from 'ionicons/icons';

addIcons({
  'alarm-outline': alarmOutline,
  'archive-outline': archiveOutline,
  'calendar-clear-outline': calendarClearOutline,
  'calendar-outline': calendarOutline,
  camera: camera,
  'camera-outline': cameraOutline,
  'car-outline': carOutline,
  'car-sport': carSport,
  'checkmark-circle': checkmarkCircle,
  'close-outline': closeOutline,
  'cloud-done-outline': cloudDoneOutline,
  'cloud-offline-outline': cloudOfflineOutline,
  'copy-outline': copyOutline,
  'create-outline': createOutline,
  'eye-outline': eyeOutline,
  list: list,
  'list-outline': listOutline,
  'locate-outline': locateOutline,
  'location-outline': locationOutline,
  map: map,
  'map-outline': mapOutline,
  navigate: navigate,
  'navigate-outline': navigateOutline,
  'notifications-outline': notificationsOutline,
  'refresh-outline': refreshOutline,
  settings: settings,
  'settings-outline': settingsOutline,
  'stop-circle': stopCircle,
  'time-outline': timeOutline,
  'trash-bin-outline': trashBinOutline,
  'trash-outline': trashOutline,
  'warning-outline': warningOutline,
});

@Component({
  selector: 'app-root',
  template: `<ion-app><ion-router-outlet></ion-router-outlet></ion-app>`,
  imports: [IonApp, IonRouterOutlet],
})
export class AppComponent {}
